export const db1 = [
  {
    id: 1,
    product: "refrigerator",
    category: "kitchen",
    brand: "samsung",

    header: "یخچال سامسونگ",
    paragraph: "یخچال فریزر 4 در فلکس هوشمند سامسونگ با ظرفیت فوق العاده بالا",
    code: "1",
    price: 6000,
    currentPrice: 6500,
    discount: "0.07",
    details: "",
  },
  {
    id: 2,
    product: "cellphone",
    category: "electronic",
    brand: "iphone",

    header: "آیفون 13 پرومکس",
    paragraph: "این محصول در صورت لزوم بازرسی، تست و بازسازی می شود",
    code: "2",
    price: 3500,
    currentPrice: 4000,
    discount: "0.12",
    details: "",
  },
  {
    id: 3,
    product: "shoes",
    category: "cloth",
    brand: "adidas",

    header: "کفش زنانه آدیداس",
    paragraph: "این کفش بسیار نرم و راحت و مناسب با سلیقه خانم ها می باشد ",
    code: "3",
    price: 2500,
    currentPrice: 3000,
    discount: "0.16",
    details: "",
  },
  {
    id: 4,
    product: "pencils",
    category: "stationary",
    brand: "faber-castell",
    header: "مداد رنگی فابرکاستل",
    paragraph: "رنگ های روشن و درخشان. از جمله رنگ های متالیک، نئون و پاستلی",
    code: "4",
    price: 1000,
    currentPrice: 1500,
    discount: "0.33",
    details: "",
  },
  {
    id: 5,
    product: "laptop",
    category: "electronic",
    brand: "apple",

    header: "مک بوک اپل",
    paragraph: "مک بوک اپل با صفحه لمسی یکی از جدید ترین و راحت ترین لپتاپها",
    code: "5",
    price: 23000,
    currentPrice: 24000,
    discount: 0.04,
    details: "",
  },
  {
    id: 6,
    product: "paper",
    category: "stationary",
    brand: "copymax",

    header: "برگه آ چهار",
    paragraph: "بسته 500 تایی برگه آچهار کپی مکس با بهترین قیمت",
    code: "6",
    price: 350,
    currentPrice: 400,
    discount: "0.12",
    details: "",
  },
  {
    id: 7,
    product: "shoes",
    category: "cloth",
    brand: "adidas",

    header: "کفش آدیداس مردانه",
    paragraph: "کفش های تنیس مردانه که برای تمرین و اجرا ساخته شده اند",
    code: "7",
    price: 2500,
    currentPrice: 3000,
    discount: "0.16",
    details: "",
  },
  {
    id: 8,
    product: "coffee",
    category: "kitchen",
    brand: "nova",
    header: "قهوه ساز نووا",
    paragraph: "طراحی شده برای دم کردن قهوه با گرم کردن و فیلتر کردن آب",
    code: "8",
    price: 1300,
    currentPrice: 2000,
    discount: "0.35",
    details: "",
  },
  {
    id: 9,
    product: "coffee",
    category: "kitchen",
    brand: "nova",

    header: "قهوه ساز نووا",
    paragraph: "طراحی شده برای دم کردن قهوه با گرم کردن و فیلتر کردن آب",
    code: "9",
    price: 1700,
    currentPrice: 2000,
    discount: "0.15",
    details: "",
  },
  {
    id: 10,
    product: "pot",
    category: "kitchen",
    brand: "vogati",

    header: "قابلمه ووگاتی",
    paragraph: "فولاد ضد زنگ، چدن یا نچسب و اشکال مختلف با طرحی بسیار زیبا",
    code: "10",
    price: 3200,
    currentPrice: 3800,
    discount: "0.15",
    details: "",
  },
  {
    id: 11,
    product: "pot",
    category: "kitchen",
    brand: "vogati",

    header: "قابلمه ووگاتی",
    paragraph: "فولاد ضد زنگ، چدن یا نچسب و اشکال مختلف با طرحی بسیار زیبا",
    code: "11",
    price: 2700,
    currentPrice: 3200,
    discount: "0.15",
    details: "",
  },
  {
    id: 12,
    product: "iron",
    category: "kitchen",
    brand: "delmonti",

    header: "اتو دلمونتی",
    paragraph: "این آهن به دلیل استحکام، دوام و توانایی خود شناخته شده است",
    code: "12",
    price: 1800,
    currentPrice: 2300,
    discount: "0.21",
    details: "",
  },
  {
    id: 13,
    product: "iron",
    category: "kitchen",
    brand: "delmonti",

    header: "اتو دلمونتی",
    paragraph: "این آهن به دلیل استحکام، دوام و توانایی خود شناخته شده است",
    code: "13",
    price: 1800,
    currentPrice: 2300,
    discount: "0.21",
    details: "",
  },
  {
    id: 14,
    product: "refrigerator",
    category: "kitchen",
    brand: "samsung",

    header: "یخچال سامسونگ",
    paragraph: "انتخاب محبوب در بین مصرف کنندگان به دلیل بهره وری انرژی آن است",
    code: "14",
    price: 22000,
    currentPrice: 24000,
    discount: "0.04",
    details: "",
  },
  {
    id: 15,
    product: "refrigerator",
    category: "kitchen",
    brand: "samsung",

    header: "یخچال سامسونگ",
    paragraph: "انتخاب محبوب در بین مصرف کنندگان به دلیل بهره وری انرژی آن است",
    code: "15",
    price: 22000,
    currentPrice: 24000,
    discount: "0.04",
    details: "",
  },
  {
    id: 16,
    product: "refrigerator",
    category: "kitchen",
    brand: "lg",

    header: "یخچال ال جی",
    paragraph: "انتخاب محبوب در بین مصرف کنندگان به دلیل بهره وری انرژی آن است",
    code: "16",
    price: 18000,
    currentPrice: 20000,
    discount: "0.1",
    details: "",
  },
  {
    id: 17,
    product: "refrigerator",
    category: "kitchen",
    brand: "lg",

    header: "یخچال ال جی",
    paragraph: "انتخاب محبوب در بین مصرف کنندگان به دلیل بهره وری انرژی آن است",
    code: "17",
    price: 18000,
    currentPrice: 20000,
    discount: "0.1",
    details: "",
  },
  {
    id: 18,
    product: "cellphone",
    category: "electronic",
    brand: "samsung",

    header: "موبایل سامسونگ",
    paragraph: "طیف گسترده ای از تلفن های همراه که نیازهای مختلف رافراهم میکند",
    code: "18",
    price: 14000,
    currentPrice: 16000,
    discount: "0.12",
    details: "",
  },
  {
    id: 19,
    product: "cellphone",
    category: "electronic",
    brand: "xiaomi",

    header: "موبایل شیاومی",
    paragraph: "طیف گسترده ای از تلفن های همراه که نیازهای مختلف رافراهم میکند",
    code: "19",
    price: 17000,
    currentPrice: 18000,
    discount: "0.05",
    details: "",
  },
  {
    id: 20,
    product: "mobile-accessory",
    category: "electronic",
    brand: "iphone",

    header: "ایرپاد اپل",
    paragraph: "هدفون های بی سیم طراحی شده برای ادغام با دستگاه های اپل",
    code: "20",
    price: 4500,
    currentPrice: 5000,
    discount: "0.1",
    details: "",
  },
  {
    id: 21,
    product: "mobile-accessory",
    category: "electronic",
    brand: "samsung",

    header: "محافظ صفحه سامسونگ",
    paragraph:
      " لوازم جانبی محافظ که برای گوشی های هوشمند سامسونگ طراحی شده است",
    code: "21",
    price: 300,
    currentPrice: 450,
    discount: "0.11",
    details: "",
  },
  {
    id: 22,
    product: "mobile-accessory",
    category: "electronic",
    brand: "xiaomi",

    header: "محافظ صفحه شیاومی",
    paragraph:
      "یک لوازم جانبی محافظ که برای گوشی های هوشمند سامسونگ طراحی شده است",
    code: "22",
    price: 300,
    currentPrice: 450,
    discount: "0.11",
    details: "",
  },
  {
    id: 23,
    product: "laptop",
    category: "electronic",
    brand: "hp",

    header: "لپتاپ اچ پی",
    paragraph: "طیف گسترده ای از لپ تاپ که نیازهای کاربران را برآورده می کنند",
    code: "23",
    price: 38000,
    currentPrice: 40000,
    discount: "0.05",
    details: "",
  },
  {
    id: 24,
    product: "laptop",
    category: "electronic",
    brand: "lenovo",

    header: "لپتاپ لنووو",
    paragraph: "طیف گسترده ای از لپ تاپ که نیازهای کاربران را برآورده می کنند",
    code: "24",
    price: 38000,
    currentPrice: 40000,
    discount: "0.05",
    details: "",
  },
  {
    id: 25,
    product: "laptop-accessory",
    category: "electronic",
    brand: "apple",

    header: "مووس اپل",
    paragraph:
      "اولین بار در سال 1998 معرفی شد و به دلیل طراحی خود شناخته شده است",
    code: "25",
    price: 4200,
    currentPrice: 5000,
    discount: "0.16",
    details: "",
  },
  {
    id: 26,
    product: "laptop-accessory",
    category: "electronic",
    brand: "sony",
    header: "هدفون سونی",
    paragraph: "انتخاب های محبوب به دلیل فناوری صدای با کیفیت بالا",
    code: "26",
    price: 3000,
    currentPrice: 3700,
    discount: "0.18",
    details: "",
  },
  {
    id: 27,
    product: "laptop-accessory",
    category: "electronic",
    brand: "apple",

    header: "کیبورد اپل",
    paragraph:
      "اولین بار در سال 1998 معرفی شد و به دلیل طراحی خود شناخته شده است",
    code: "27",
    price: 6200,
    currentPrice: 7500,
    discount: "0.17",
    details: "",
  },
  {
    id: 28,
    product: "pc-accessory",
    category: "electronic",
    brand: "intel",

    header: "مادربورد اینتل",
    paragraph: " برد اصلی در یک سیستم که اجزای سخت افزاری را به هم متصل می کند",
    code: "28",
    price: 36000,
    currentPrice: 38000,
    discount: "0.05",
    details: "",
  },
  {
    id: 29,
    product: "pc-accessory",
    category: "electronic",
    brand: "nvidia",

    header: "هارد انویدیا",
    paragraph:
      "به دلیل های سخت افزار خود در واحد پردازش گرافیکی شناخته شده است",
    code: "29",
    price: 24000,
    currentPrice: 26000,
    discount: "0.07",
    details: "",
  },
  {
    id: 30,
    product: "t-shirt",
    category: "cloth",
    brand: "nike",
    header: "تیشرت نایک",
    paragraph: "این محصول در سبک ها، رنگ ها و طرح های مختلف مختلف عرضه می شود",
    code: "30",
    price: 1400,
    currentPrice: 1900,
    discount: "0.26",
    details: "",
  },
  {
    id: 31,
    product: "t-shirt",
    category: "cloth",
    brand: "puma",

    header: "تیشرت پوما",
    paragraph: "این محصول در سبک ها، رنگ ها و طرح های مختلف  مختلف عرضه می شود",
    code: "31",
    price: 1400,
    currentPrice: 1900,
    discount: "0.26",
    details: "",
  },
];
